export const SET_ERROR = 'SET_ERROR';
export const SET_LOADER = 'SET_LOADER';
export const ADD_SEARCH_TEXT = 'ADD_SEARCH_TEXT';
export const ADD_SEARCH_TYPE = 'ADD_SEARCH_TYPE';
export const ADD_USER_SEARCH_RESULT = 'ADD_USER_SEARCH_RESULT';
export const ADD_REPO_SEARCH_RESULT = 'ADD_REPO_SEARCH_RESULT';
